repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^(watcher/.+)?[^/]+\.py$
        args: [--config, pyproject.toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.11.1
          - pyflakes==3.2.0
          - pycodestyle==2.11.1
          - mccabe==0.7.0
        files: ^(watcher/.+)?[^/]+\.py$
        args: [--config, setup.cfg]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^(watcher/.+)?[^/]+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
